In [67]:
import numpy as np
import heapq
import random

Custo de um nó:

Custo Total = Custo G + Custo H

Custo G = Custo de Geração
Custo H = Custo Heurístico


A-star

f-score = g_score + h_score

g_score = qnts passos eu dei para chegar na célula
h_score = estimativa de qnts passos eu vou precisar dar pra chegar no objetivo



- ver quais caminhos pode ir
- calcular f_score

In [53]:
def inicializar_matriz():
    return np.zeros((11,11),dtype=int)

In [69]:
def gerar_bases(matriz):

    # 10 random numbers entre 0 e 120
    pontos = random.sample(range(121),10)

    for ponto in pontos:
        linha = ponto // 11
        coluna = ponto % 11
        matriz[linha][coluna] = 1
    
    return matriz

#matriz = gerar_bases()

In [70]:
matriz = inicializar_matriz()
matriz_com_bases = gerar_bases(matriz)

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]])

In [54]:
# ocupação de quadrado e vizinhos

def ocupar_celula(matriz,linha,coluna):
    matriz[linha][coluna]=1

    for i in range(-1,2):
        for j in range(-1,2):
            nova_linha = linha + i
            nova_coluna = coluna + j
            if 0 <= nova_linha < 11 and 0 <= nova_coluna < 11:
                matriz[nova_linha][nova_coluna] = 1

In [55]:
def find_melhor_posicao(matriz):

    melhor_posicao = None
    max_ocupacao = 9


    for linha in range(11):
        for coluna in range(11):
        
 

In [59]:
matriz = inicializar_matriz()

In [60]:
matriz

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [66]:
primeiro_centro = matriz[1][1]



nova_matriz = np.array([], dtype=int)
nova_matriz = np.append(nova_matriz,primeiro_centro)

nova_matriz

array([1, 2, 3, 4])

In [50]:
matriz[0][0]

0

In [58]:
melhor_posicao = find_melhor_posicao(matriz)

ocupar_celula(matriz, melhor_posicao[0], melhor_posicao[1])



TypeError: 'NoneType' object is not subscriptable

In [ ]:
print("Matriz inicial:")
print(matriz)

print("Melhor posição para ocupar:")
print(f"{melhor_posicao}")

Matriz inicial:
[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
Melhor posição para ocupar:


NameError: name 'melhor_posicao' is not defined