In [1]:
import numpy as np
import heapq

Custo de um nó:

Custo Total = Custo G + Custo H

Custo G = Custo de Geração
Custo H = Custo Heurístico


In [4]:
def inicializar_matriz():
    return np.zeros((11,11),dtype=int)

In [5]:
# ocupação de quadrado e vizinhos

def ocupar_celula(matriz,linha,coluna):
    matriz[linha][coluna]=1

    for i in range(-1,2):
        for j in range(-1,2):
            nova_linha = linha + i
            nova_coluna = coluna + j
            if 0 <= nova_linha < 11 and 0 <= nova_coluna < 11:
                matriz[nova_linha][nova_coluna] = 1

In [7]:
def find_melhor_posicao(matriz):

    melhor_linha = 0
    melhor_coluna = 0
    max_ocupacao = 0


    for linha in range(11):
        for coluna in range(11):
            ocupacao_atual = np.sum(matriz[linha-1:linha+2, coluna-1:coluna+2])
            if ocupacao_atual > max_ocupacao:
                max_ocupacao = ocupacao_atual
                melhor_linha = linha
                melhor_coluna = coluna

    return melhor_linha, melhor_coluna
 

In [8]:
matriz = inicializar_matriz()

In [9]:
matriz

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [10]:
melhor_linha, melhor_coluna = find_melhor_posicao(matriz)

ocupar_celula(matriz, melhor_linha, melhor_coluna)



In [11]:
print("Matriz inicial:")
print(matriz)

print("Melhor posição para ocupar:")
print(f"{melhor_linha},{melhor_coluna}")

Matriz inicial:
[[1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
Melhor posição para ocupar:
0,0
