In [1]:
import numpy as np
import heapq

Custo de um nó:

Custo Total = Custo G + Custo H

Custo G = Custo de Geração (no q eu quero visitar + atual)

Custo H = Custo Heurístico


In [2]:
def inicializar_matriz():
    return np.zeros((11,11),dtype=int)

In [5]:
# ocupação de quadrado e vizinhos

def ocupar_celula(matriz,linha,coluna):
    matriz[linha][coluna]=1

    for i in range(-1,2):
        for j in range(-1,2):
            nova_linha = linha + i
            nova_coluna = coluna + j
            if 0 <= nova_linha < 11 and 0 <= nova_coluna < 11:
                matriz[nova_linha][nova_coluna] = 1

In [7]:
def find_melhor_posicao(matriz):

    melhor_linha = 0
    melhor_coluna = 0
    max_ocupacao = 0


    for linha in range(11):
        for coluna in range(11):
            ocupacao_atual = np.sum(matriz[linha-1:linha+2, coluna-1:coluna+2])
            if ocupacao_atual > max_ocupacao:
                max_ocupacao = ocupacao_atual
                melhor_linha = linha
                melhor_coluna = coluna

    return melhor_linha, melhor_coluna
 

In [3]:
matriz = inicializar_matriz()

In [15]:
for i in range(11):
    for j in range(11):
        print(f'{(i,j)}', end=',')

(0, 0),(0, 1),(0, 2),(0, 3),(0, 4),(0, 5),(0, 6),(0, 7),(0, 8),(0, 9),(0, 10),(1, 0),(1, 1),(1, 2),(1, 3),(1, 4),(1, 5),(1, 6),(1, 7),(1, 8),(1, 9),(1, 10),(2, 0),(2, 1),(2, 2),(2, 3),(2, 4),(2, 5),(2, 6),(2, 7),(2, 8),(2, 9),(2, 10),(3, 0),(3, 1),(3, 2),(3, 3),(3, 4),(3, 5),(3, 6),(3, 7),(3, 8),(3, 9),(3, 10),(4, 0),(4, 1),(4, 2),(4, 3),(4, 4),(4, 5),(4, 6),(4, 7),(4, 8),(4, 9),(4, 10),(5, 0),(5, 1),(5, 2),(5, 3),(5, 4),(5, 5),(5, 6),(5, 7),(5, 8),(5, 9),(5, 10),(6, 0),(6, 1),(6, 2),(6, 3),(6, 4),(6, 5),(6, 6),(6, 7),(6, 8),(6, 9),(6, 10),(7, 0),(7, 1),(7, 2),(7, 3),(7, 4),(7, 5),(7, 6),(7, 7),(7, 8),(7, 9),(7, 10),(8, 0),(8, 1),(8, 2),(8, 3),(8, 4),(8, 5),(8, 6),(8, 7),(8, 8),(8, 9),(8, 10),(9, 0),(9, 1),(9, 2),(9, 3),(9, 4),(9, 5),(9, 6),(9, 7),(9, 8),(9, 9),(9, 10),(10, 0),(10, 1),(10, 2),(10, 3),(10, 4),(10, 5),(10, 6),(10, 7),(10, 8),(10, 9),(10, 10),

In [10]:
melhor_linha, melhor_coluna = find_melhor_posicao(matriz)

ocupar_celula(matriz, melhor_linha, melhor_coluna)



In [11]:
print("Matriz inicial:")
print(matriz)

print("Melhor posição para ocupar:")
print(f"{melhor_linha},{melhor_coluna}")

Matriz inicial:
[[1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
Melhor posição para ocupar:
0,0
